site_name: 'Handwrite'
site_description: 'Official Site for Handwrite'
site_author: 'Team Handwrite'
site_url: 'https://cod-ed.github.io/handwrite'

# Repository
repo_name: 'cod-ed/handwrite'
repo_url: 'https://github.com/cod-ed/handwrite'

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Usage: 'usage.md'
  - Contributing: 'contributing.md'
  - Credits: 'credits.md'


theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: 'black'
    accent: 'white'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  icon:
    logo: fontawesome/solid/pen-square

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list

