site_name: "Handwrite"
site_description: "Official Site for Handwrite"
site_author: "Team Handwrite"
site_url: "https://builtree.github.io/handwrite"

# Repository
repo_name: "builtree/handwrite"
repo_url: "https://github.com/builtree/handwrite"

nav:
    - Home: "index.md"
    - Installation: "installation.md"
    - Usage: "usage.md"
    - Contributing: "contributing.md"
    - Credits: "credits.md"
    - Documentation:
          - Converters:
                - SHEETtoPNG: "api/sheettopng.md"
                - PNGtoSVG: "api/pngtosvg.md"
                - SVGtoTTF: "api/svgtottf.md"

theme:
    name: material
    features:
        - navigation.sections
        # - navigation.tabs
    palette:
        primary: "black"
        accent: "white"
    font:
        text: "Ubuntu"
        code: "Ubuntu Mono"
    icon:
        logo: fontawesome/solid/pen-square

plugins:
    - mkdocstrings

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - footnotes
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde
    - attr_list
